name: apppresao
description: A new Flutter project.

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Para SQLite
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2

  # Para datas formatadas
  intl: ^0.19.0

  # Para gerenciar estado simples
  provider: ^6.1.2

  # Para hash de senha (ex: SHA-256)
  crypto: ^3.0.3